version: "3"
services:
  java-app:
    container_name: my-java-app
    image: nirdeshkumar02/jenkins-java-app:1.1.8-6
    environment:
      - DB_USER=user
      - DB_PWD=pass
      - DB_SERVER=mysql
      - DB_NAME=my-app-db
    ports:
      - 8080:8080
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=my-app-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    volumes:
      - mysql-data:/var/lib/mysql
  phpmyadmin:
    container_name: myadmin
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - 8083:80
volumes:
  mysql-data:
    driver: local
