---
- name: Deploying Server Dependencies for Nexus
  hosts: 172.31.87.144
  become: true
  tasks:
    - name: Update apt and repo cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install java 8
      apt: name=openjdk-8-jre-headless
    - name: Install net-tools
      apt: name=net-tools

- name: Download and Unpack the Nexus Installer
  hosts: 172.31.87.144
  become: true
  tasks:
    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: nexus-installer # Storing the get_url result to nexus-installer variable as latest version changed frequently

    - name: Unpack the nexus installer
      unarchive:
        src: "{{nexus-installer.dest}}" # Using the above stored variable finding the nexus-installer with version
        dest: /opt/
        remote_src: yes # telling unarchive module to check the unpack file on remote src

    - name: Find Nexus Folder
      find:
        paths: /opt/
        pattern: "nexus-*"
        file_type: directory
      register: find_folder_name

    - name: Renaming Nexus Folder
      shell: mv {{find_folder_name.files[0].path}} /opt/nexus
