---
- name: Deploying NodeJS Applicaton Dependencies on server 
  hosts: 172.31.87.144
  become: true
  become_user: root
  tasks:
    - name: Update apt and repo cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install node and npm
      apt:
        pkg:
          - nodejs
          - npm
    - name: Create Linux User
      user: 
        name: nirdesh
        password: nirdesh 
        group: admin

- name: Deploy the node application
  hosts: 172.31.87.144
  become: yes  
  become_user: nirdesh
  # define variable in this file 
  vars:
    - location: /home/ubuntu
    - version: 1.0.0
    - destination: /home/nirdesh
  # define variable in outside the file and refrence it here
  # vars_files:
  #   - project-vars
  tasks:
    - name: Unpack the app tar file and copy its data to remote server
      unarchive:
        src: "{{location}}/Ansible-Learning/nodejs-app-{{version}}.tgz"
        dest: "{{destination}}"

    - name: Install Dependencies
      npm:
        path: "{{destination}}/package"
    
    #  As command and shell modules ain't idempotent so we should use conditional statement to provide idempotency
    - name: Start the Applicaton
      command:
        chdir: "{{destination}}/package/app"
        cmd: node server
      # use this module to run node command in background othewise it will block the terminal and never exit 
      async: 1000
      poll: 0

    - name: Ensure Applicaton is running
      shell: ps aux | grep node
      register: app_status # hepls in storing output in providing variable 
    
    - debug: msg={{app_status.stdout_lines}}

